baseURL = "https://jmbravo.com/"
languageCode = "es-es"
defaultContentLanguage = "es"
title = "jmbravo.com"

[params]
  description = "José María Bravo: fantasía, terror y otras hierbas literarias."

[[menu.main]]
  name = "inicio"
  url = "/"
  weight = 1

[[menu.main]]
  name = "blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "libros"
  url = "/libros/"
  weight = 3

[[menu.main]]
  name = "sobre mí"
  url = "/sobre-mi/"
  weight = 4

[[menu.main]]
  name = "contacto"
  url = "/contacto/"
  weight = 5
