baseURL = "https://jmbravo.com/"
languageCode = "es-es"
defaultContentLanguage = "es"
title = "Sitio web de José María Bravo Lineros"

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[params]
  description = "Página del escritor José María Bravo Lineros: fantasía y otras hierbas literarias."

#[[menu.main]]
#  name = "Proyectos"
#  url = "/proyectos/"
#  weight = 1

[[menu.main]]
  name = "Libros"
  url = "/libros/"
  weight = 2

[[menu.main]]
  name = "Obra"
  url = "/obra/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4

[[menu.main]]
  name = "Descargas"
  url = "/descargas/"
  weight = 5

[[menu.footer]]
  name = "Sobre mí"
  url = "/sobre-mi/"
  weight = 1

[[menu.footer]]
  name = "Contacto"
  url = "/contacto/"
  weight = 2

[[menu.footer]]
  name = "Aviso legal"
  url = "/aviso-legal/"
  weight = 3

[[menu.footer]]
  name = "Privacidad"
  url = "/privacidad/"
  weight = 4
